// This file is autogenerated

import {resizeBilinear as resizeBilinear_image} from '@tensorflow/tfjs-core/dist/ops/image/resize_bilinear';
export const image = {
	resizeBilinear: resizeBilinear_image,
};
import {depthwiseConv2d as depthwiseConv2d_fused} from '@tensorflow/tfjs-core/dist/ops/fused/depthwise_conv2d';
import {conv2d as conv2d_fused} from '@tensorflow/tfjs-core/dist/ops/fused/conv2d';
export const fused = {
	depthwiseConv2d: depthwiseConv2d_fused,
	conv2d: conv2d_fused,
};
export {mul} from '@tensorflow/tfjs-core/dist/ops/mul';
export {sub} from '@tensorflow/tfjs-core/dist/ops/sub';
export {conv2d} from '@tensorflow/tfjs-core/dist/ops/conv2d';
export {add} from '@tensorflow/tfjs-core/dist/ops/add';
export {relu6} from '@tensorflow/tfjs-core/dist/ops/relu6';
export {depthwiseConv2d} from '@tensorflow/tfjs-core/dist/ops/depthwise_conv2d';
export {mean} from '@tensorflow/tfjs-core/dist/ops/mean';
export {squeeze} from '@tensorflow/tfjs-core/dist/ops/squeeze';
export {minimum} from '@tensorflow/tfjs-core/dist/ops/minimum';
export {maximum} from '@tensorflow/tfjs-core/dist/ops/maximum';
export {cast} from '@tensorflow/tfjs-core/dist/ops/cast';
export {tensor1d} from '@tensorflow/tfjs-core/dist/ops/tensor1d';
export {stridedSlice} from '@tensorflow/tfjs-core/dist/ops/strided_slice';
export {range} from '@tensorflow/tfjs-core/dist/ops/range';
export {less} from '@tensorflow/tfjs-core/dist/ops/less';
export {expandDims} from '@tensorflow/tfjs-core/dist/ops/expand_dims';
export {addN} from '@tensorflow/tfjs-core/dist/ops/add_n';
export {reshape} from '@tensorflow/tfjs-core/dist/ops/reshape';
export {stack} from '@tensorflow/tfjs-core/dist/ops/stack';
export {concat} from '@tensorflow/tfjs-core/dist/ops/concat';
export {sigmoid} from '@tensorflow/tfjs-core/dist/ops/sigmoid';
export {slice} from '@tensorflow/tfjs-core/dist/ops/slice';
export {transpose} from '@tensorflow/tfjs-core/dist/ops/transpose';
export {tile} from '@tensorflow/tfjs-core/dist/ops/tile';
export {unstack} from '@tensorflow/tfjs-core/dist/ops/unstack';
export {exp} from '@tensorflow/tfjs-core/dist/ops/exp';
export {relu} from '@tensorflow/tfjs-core/dist/ops/relu';
export {maxPool} from '@tensorflow/tfjs-core/dist/ops/max_pool';
export {pad} from '@tensorflow/tfjs-core/dist/ops/pad';
export {conv2dTranspose} from '@tensorflow/tfjs-core/dist/ops/conv2d_transpose';
export {scalar} from '@tensorflow/tfjs-core/dist/ops/scalar';
export {prelu} from '@tensorflow/tfjs-core/dist/ops/prelu';