/**
 * @license
 * Copyright 2021 Google LLC. All Rights Reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * =============================================================================
 */

// This file is autogenerated.


import {registerKernel} from '@tensorflow/tfjs-core/dist/base';
import '@tensorflow/tfjs-core/dist/base_side_effects';
export * from '@tensorflow/tfjs-core/dist/base';
export * from '@tensorflow/tfjs-converter';

//backend = webgl
export * from '@tensorflow/tfjs-backend-webgl/dist/base';
import {multiplyConfig as Multiply_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Multiply';
registerKernel(Multiply_webgl);
import {subConfig as Sub_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Sub';
registerKernel(Sub_webgl);
import {conv2DConfig as Conv2D_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Conv2D';
registerKernel(Conv2D_webgl);
import {addConfig as Add_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Add';
registerKernel(Add_webgl);
import {relu6Config as Relu6_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Relu6';
registerKernel(Relu6_webgl);
import {depthwiseConv2dNativeConfig as DepthwiseConv2dNative_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/DepthwiseConv2dNative';
registerKernel(DepthwiseConv2dNative_webgl);
import {meanConfig as Mean_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Mean';
registerKernel(Mean_webgl);
import {reshapeConfig as Reshape_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Reshape';
registerKernel(Reshape_webgl);
import {castConfig as Cast_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Cast';
registerKernel(Cast_webgl);
import {resizeBilinearConfig as ResizeBilinear_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/ResizeBilinear';
registerKernel(ResizeBilinear_webgl);
import {sliceConfig as Slice_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Slice';
registerKernel(Slice_webgl);
import {padV2Config as PadV2_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/PadV2';
registerKernel(PadV2_webgl);
import {realDivConfig as RealDiv_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/RealDiv';
registerKernel(RealDiv_webgl);
import {expandDimsConfig as ExpandDims_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/ExpandDims';
registerKernel(ExpandDims_webgl);
import {sigmoidConfig as Sigmoid_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Sigmoid';
registerKernel(Sigmoid_webgl);
import {argMaxConfig as ArgMax_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/ArgMax';
registerKernel(ArgMax_webgl);
import {floorDivConfig as FloorDiv_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/FloorDiv';
registerKernel(FloorDiv_webgl);
import {concatConfig as Concat_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Concat';
registerKernel(Concat_webgl);
import {minimumConfig as Minimum_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Minimum';
registerKernel(Minimum_webgl);
import {maximumConfig as Maximum_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Maximum';
registerKernel(Maximum_webgl);
import {cropAndResizeConfig as CropAndResize_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/CropAndResize';
registerKernel(CropAndResize_webgl);
import {greaterConfig as Greater_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Greater';
registerKernel(Greater_webgl);
import {identityConfig as Identity_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Identity';
registerKernel(Identity_webgl);
import {stridedSliceConfig as StridedSlice_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/StridedSlice';
registerKernel(StridedSlice_webgl);
import {rangeConfig as Range_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Range';
registerKernel(Range_webgl);
import {unpackConfig as Unpack_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Unpack';
registerKernel(Unpack_webgl);
import {lessConfig as Less_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Less';
registerKernel(Less_webgl);
import {packConfig as Pack_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Pack';
registerKernel(Pack_webgl);
import {addNConfig as AddN_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/AddN';
registerKernel(AddN_webgl);
import {fusedDepthwiseConv2DConfig as FusedDepthwiseConv2D_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/FusedDepthwiseConv2D';
registerKernel(FusedDepthwiseConv2D_webgl);
import {fusedConv2DConfig as FusedConv2D_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/FusedConv2D';
registerKernel(FusedConv2D_webgl);
import {transposeConfig as Transpose_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Transpose';
registerKernel(Transpose_webgl);
import {expConfig as Exp_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Exp';
registerKernel(Exp_webgl);
import {tileConfig as Tile_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Tile';
registerKernel(Tile_webgl);
import {nonMaxSuppressionV3Config as NonMaxSuppressionV3_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/NonMaxSuppressionV3';
registerKernel(NonMaxSuppressionV3_webgl);

//backend = cpu
export * from '@tensorflow/tfjs-backend-cpu/dist/base';
import {multiplyConfig as Multiply_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Multiply';
registerKernel(Multiply_cpu);
import {subConfig as Sub_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Sub';
registerKernel(Sub_cpu);
import {conv2DConfig as Conv2D_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Conv2D';
registerKernel(Conv2D_cpu);
import {addConfig as Add_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Add';
registerKernel(Add_cpu);
import {relu6Config as Relu6_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Relu6';
registerKernel(Relu6_cpu);
import {depthwiseConv2dNativeConfig as DepthwiseConv2dNative_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/DepthwiseConv2dNative';
registerKernel(DepthwiseConv2dNative_cpu);
import {meanConfig as Mean_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Mean';
registerKernel(Mean_cpu);
import {reshapeConfig as Reshape_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Reshape';
registerKernel(Reshape_cpu);
import {castConfig as Cast_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Cast';
registerKernel(Cast_cpu);
import {resizeBilinearConfig as ResizeBilinear_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/ResizeBilinear';
registerKernel(ResizeBilinear_cpu);
import {sliceConfig as Slice_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Slice';
registerKernel(Slice_cpu);
import {padV2Config as PadV2_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/PadV2';
registerKernel(PadV2_cpu);
import {realDivConfig as RealDiv_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/RealDiv';
registerKernel(RealDiv_cpu);
import {expandDimsConfig as ExpandDims_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/ExpandDims';
registerKernel(ExpandDims_cpu);
import {sigmoidConfig as Sigmoid_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Sigmoid';
registerKernel(Sigmoid_cpu);
import {argMaxConfig as ArgMax_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/ArgMax';
registerKernel(ArgMax_cpu);
import {floorDivConfig as FloorDiv_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/FloorDiv';
registerKernel(FloorDiv_cpu);
import {concatConfig as Concat_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Concat';
registerKernel(Concat_cpu);
import {minimumConfig as Minimum_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Minimum';
registerKernel(Minimum_cpu);
import {maximumConfig as Maximum_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Maximum';
registerKernel(Maximum_cpu);
import {cropAndResizeConfig as CropAndResize_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/CropAndResize';
registerKernel(CropAndResize_cpu);
import {greaterConfig as Greater_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Greater';
registerKernel(Greater_cpu);
import {identityConfig as Identity_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Identity';
registerKernel(Identity_cpu);
import {stridedSliceConfig as StridedSlice_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/StridedSlice';
registerKernel(StridedSlice_cpu);
import {rangeConfig as Range_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Range';
registerKernel(Range_cpu);
import {unpackConfig as Unpack_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Unpack';
registerKernel(Unpack_cpu);
import {lessConfig as Less_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Less';
registerKernel(Less_cpu);
import {packConfig as Pack_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Pack';
registerKernel(Pack_cpu);
import {addNConfig as AddN_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/AddN';
registerKernel(AddN_cpu);
import {fusedDepthwiseConv2DConfig as FusedDepthwiseConv2D_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/FusedDepthwiseConv2D';
registerKernel(FusedDepthwiseConv2D_cpu);
import {fusedConv2DConfig as FusedConv2D_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/FusedConv2D';
registerKernel(FusedConv2D_cpu);
import {transposeConfig as Transpose_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Transpose';
registerKernel(Transpose_cpu);
import {expConfig as Exp_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Exp';
registerKernel(Exp_cpu);
import {tileConfig as Tile_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/Tile';
registerKernel(Tile_cpu);
import {nonMaxSuppressionV3Config as NonMaxSuppressionV3_cpu} from '@tensorflow/tfjs-backend-cpu/dist/kernels/NonMaxSuppressionV3';
registerKernel(NonMaxSuppressionV3_cpu);